---
  - name: Print os facts
    hosts: ubuntu, centos7, localhost
   # become: yes
   # become_user: root
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
